eduvpn/python-eduvpn-client

eduvpn/steps/browser.py

We were experiencing a phase 2 "invalid_request".
This fixed this issue. I have no clue to check if is has any impact. Let me know your thougts.

Include client_id in phase 2

---

eduvpn/manager.py
eduvpn/other_nm.py

This should address issue #189 
This is a bit of a workaround since `eduvpn.other_nm` is such a mess, but as far as i know it does the trick.

don't try to access connection if no permissions, issue #189

---

Makefile
README.md
doc/requirements.txt
docker/mypy.docker
docker/pep8.docker
docker/pytest_centos_8.docker
docker/pytest_debian_buster.docker
docker/pytest_fedora_31.docker
docker/pytest_fedora_32.docker
docker/pytest_ubuntu_bionic.docker
docker/pytest_ubuntu_focal.docker
docker/rpm_centos_8.docker
docker/rpm_fedora_32.docker
eduvpn/crypto.py
eduvpn/nm.py
eduvpn/ui/backend.py
eduvpn/ui/ui.py
eduvpn/utils.py
setup.py
share/eduvpn/builder/mainwindow.ui

2.0.x issue265

---

eduvpn/nm.py
eduvpn/ui/__main__.py
eduvpn/ui/backend.py
eduvpn/ui/ui.py

Temporary workaround, connection is sometimes created too late while according to the logging the connection is already created. Need to find the correct event to sync on. But this fixes the issue for now, let's first tackle other issues and do the real fix on the side.

2.0.x issue264 2

---

README.md
doc/introduction.rst

The package list can probably shorter but this is what is also used in the Makefile. Testing it all by installing fresh VMs is too time consuming for now.

Update the installation documentation

---

doc/introduction.rst

Doc update2

---

eduvpn/remote.py
eduvpn/ui/__main__.py
eduvpn/ui/ui.py
share/eduvpn/builder/mainwindow.ui

Start adding exception handling, currently when retrieval of initial info is failing and when the type url can't resolve.

2.0.x #254

---

eduvpn/settings.py

Additional public keys have been added to the list of acceptable keys for signing the discovery files
#281

2.0.x #281

---

eduvpn/ui/ui.py

# 283: Fix bug when handling secure internet servers

---

doc/introduction.rst

Fix typo in documentation

---

doc/introduction.rst
eduvpn/cli.py
eduvpn/remote.py
eduvpn/settings.py
eduvpn/ui/backend.py
eduvpn/ui/ui.py

2.0.x issue251 2

---

eduvpn/actions.py
eduvpn/cli.py
eduvpn/menu.py
eduvpn/nm.py
eduvpn/storage.py
eduvpn/type.py
eduvpn/ui/backend.py
eduvpn/ui/ui.py
tests/test_actions.py
tests/test_menu.py

@amarsman please check the TODO's in the UI, the flow probably needs to be changed.

Store metadata for all previous profiles 

---

doc/introduction.rst

the existing explanation left users clueless.

proper use of sudo

---

eduvpn/actions.py
eduvpn/cli.py
eduvpn/storage.py
eduvpn/ui/ui.py
eduvpn/ui/vpn_connection.py

#295 Remove storage from vpn_connection, fix bugs, improve startup when there is already a connection.
Started adding documentation, more bugs needs to be fixed.
cli needs to be tested also.

2.0.x issue295

---

eduvpn.spec
eduvpn/ui/backend.py
eduvpn/ui/ui.py
eduvpn/ui/utils.py
eduvpn/ui/vpn_connection.py

2.0.x issues

---

eduvpn.spec
eduvpn/ui/backend.py
eduvpn/ui/ui.py
eduvpn/ui/utils.py
eduvpn/ui/vpn_connection.py

Reverts eduvpn/python-eduvpn-client#319

Revert "2.0.x issues"

---

rpm/eduvpn_centos8.spec
rpm/eduvpn_fedora.spec

Suggested fix #316.
I had this ready anyway, so feel free to use or dismiss my patch.

install: Add openvpn requirement to rpm packages

---

eduvpn/interface/event.py
eduvpn/interface/state.py
eduvpn/server.py
eduvpn/ui/ui.py
eduvpn/utils.py

Implement the location choice.

Implement choosing a secure internet location.

---

eduvpn/app.py
eduvpn/interface/event.py
eduvpn/interface/state.py
eduvpn/network.py
eduvpn/nm.py
eduvpn/server.py
eduvpn/ui/ui.py

Show details on the current connection.
Fix issue reported by @gijzelaerr; calling function from wrong thread.

Show (some) connection details

---

eduvpn/interface/__init__.py
eduvpn/interface/event.py
eduvpn/interface/state.py
eduvpn/interface/transition.py
eduvpn/network.py
eduvpn/remote.py
eduvpn/server.py
eduvpn/ui/ui.py
eduvpn/ui/utils.py
share/eduvpn/builder/mainwindow.ui

* Handle invalid profile responses (issue #329)
* Server support details have been turned into links
* Keep polling network for status if unknown
* Interface always shows feedback on internal state
Refer to the commit messages for the full details.

Fix issue #329

---

.github/ISSUE_TEMPLATE/new_feature.md

This allows people to directly create feature request issues, so they can be created as easily as bug reports.
I'm not sure there's any specific details we can ask for so I've kept it simple.

Add a github issue template for feature requests.

---

eduvpn/app.py
eduvpn/i18n.py

This fixes:
```
/home/parallels/Work/surfnet/python-eduvpn-client/eduvpn/nm.py:29: Warning: g_main_context_push_thread_default: assertion 'acquired_context' failed
return NM.Client.new(None)
/home/parallels/Work/surfnet/python-eduvpn-client/eduvpn/nm.py:29: Warning: g_main_context_pop_thread_default: assertion 'g_queue_peek_head (stack) == context' failed
return NM.Client.new(None)
```

Fix calling NM from background thread.

---

eduvpn/i18n.py
eduvpn/network.py
eduvpn/ui/ui.py
share/eduvpn/builder/mainwindow.ui
share/locale/de_DE/LC_MESSAGES/eduVPN.po

This applies fixes to the translation feature. Refer to the individual commits for details.

Fix translations

---

eduvpn/i18n.py
eduvpn/ui/ui.py

This fixes an issue with translations where not all text is translated.

Translation fix

---

eduvpn/network.py
eduvpn/nm.py

Fix issue #269.

---

eduvpn/remote.py

Fix for server addresses not ending in `/`.

Fix issue 360

---

eduvpn/crypto.py

Fix issue 362

---

eduvpn/ui/search.py

Truncate long names with ellipsis.

Fix issue #367; avoid horizontal scrolling search results.

---

eduvpn/actions.py
eduvpn/app.py
eduvpn/i18n.py
eduvpn/interface/event.py
eduvpn/interface/transition.py
eduvpn/network.py
eduvpn/oauth2/challenge.py
eduvpn/oauth2/http.py
eduvpn/settings.py
eduvpn/ui/__main__.py
eduvpn/ui/ui.py
eduvpn/variants.py
share/eduvpn/builder/mainwindow.ui
tests/test_flow.py
tests/test_oauth.py
tests/utils.py

Implement `Let's connect` variant of the application.

---

.github/workflows/containers.yml
doc/developer.rst
docker/pytest_centos_8.docker
docker/pytest_debian_buster.docker
docker/pytest_fedora_33.docker
docker/pytest_ubuntu_bionic.docker
docker/pytest_ubuntu_focal.docker
docker/rpm_centos_8.docker
docker/rpm_fedora_33.docker
tests/test_connect.py

Add an integration test that connects to an actual server, given as an environment variable.

Add integration test.

---

.github/workflows/containers.yml
docker/mypy.docker
eduvpn/oauth2/http.py
tests/test_connect.py
tests/test_flow.py
tests/utils.py

The test now runs successfully on local PRs only (ie. not from a fork).

Fix integration test by running in a GLib event loop

---

eduvpn/settings.py

As per https://github.com/eduvpn/documentation/blob/v2/SERVER_DISCOVERY.md#signatures

update discovery public keys

---

eduvpn/storage.py

This fixes an issue that was reported off-github.

Fix deserialization issue on python<3.7.

---

eduvpn/app.py
eduvpn/interface/error.py
eduvpn/interface/event.py
eduvpn/interface/state.py
eduvpn/menu.py
eduvpn/server.py
eduvpn/ui/ui.py

This suggestion originates in #380.

Show error message when receiving a bad signatures from the server.

---

LICENSE
eduvpn.spec

update license references to GPLv3+

---

.github/workflows/containers.yml
docker/pylama.docker
eduvpn/menu.py
eduvpn/state_machine.py
setup.py
tests/test_actions.py
tests/test_flow.py
tests/test_nm.py
tests/test_state_machine.py

This collects some of the work that didn't make it into 2.1.
Including:
* A number of additional automated code checks using pylama
* Fixes for issues found by pylama
* Support for subscribing to state machine level changes.

Various improvements

---

eduvpn/ui/ui.py

Fix issue with missing country flags.

---

eduvpn/nm.py
setup.py

issue #167
resolves this for both IPv4 and IPv6 and do not use a callback
which would result in race condition

fix split tunnel

---

eduvpn/nm.py
eduvpn/ui/ui.py

UI & NM: Check if a device of the primary connection is managed

---

CHANGES.md
eduvpn.spec
setup.py

- Add changelog for 2.2.1 to CHANGES.md
- Add changelog for 2.2.0 to CHANGES.md (was missing)
- Update version numbers

Prepare release 2.2.1

---

CHANGES.md
share/eduvpn/builder/mainwindow.ui

Remove change location button

---

Makefile

Update makefile centos paths

---

CHANGES.md

obtained using:
```
git log --tags --simplify-by-decoration --pretty="format:%ci %d"
```

add dates of releases

---

eduvpn/app.py
eduvpn/connection.py
eduvpn/crypto.py
eduvpn/interface/event.py
eduvpn/interface/state.py
eduvpn/nm.py
eduvpn/remote.py
eduvpn/server.py
eduvpn/session.py
eduvpn/storage.py
eduvpn/ui/ui.py
eduvpn/utils.py

These changes update the API to [version V3](https://github.com/eduvpn/documentation/blob/v3/API.md).
This work is the foundation for enabling WireGuard support, introducing some changes (and 4 TODOs) that are required when handling multiple protocols.

Update API to V3.

---

eduvpn/nm.py

Attempts to fix #479 
The problem with using `get_timestamp` is the fact that the NM Python client seems to cache it (?), we could create a fresh NM.client (it's cached using a lru cache right now) but this would give us thread warnings.
Let's try to get the connection duration using Dbus directly which should hopefully give us the correct values.

Timestamp: Use dbus directly instead of NM

---

setup.py

add long description for pypi

---

CHANGES.md
eduvpn.spec
eduvpn/i18n.py
setup.py

- Updates changelog
- Updates version numbers
- Tiny mypy fix

Prepare for v3 release

---

eduvpn/nm.py

This simplifies the code a lot and should hopefully solve issue #493 
Needs a confirm that this even works

NM: Simplify getting interface/IP info and fix inconsistencies

---

CHANGES.md
eduvpn.spec
eduvpn/app.py
eduvpn/cli.py
eduvpn/config.py
eduvpn/connection.py
eduvpn/keyring.py
eduvpn/nm.py
eduvpn/ovpn.py
eduvpn/server.py
eduvpn/settings.py
eduvpn/ui/app.py
eduvpn/ui/search.py
eduvpn/ui/stats.py
eduvpn/ui/ui.py
eduvpn/ui/utils.py
eduvpn/utils.py
eduvpn/variants.py
setup.py
share/eduvpn/builder/mainwindow.ui

Prepare new pre-release

---

CHANGES.md
eduvpn.spec
eduvpn/app.py
eduvpn/nm.py
eduvpn/ui/ui.py
eduvpn/ui/utils.py
eduvpn/utils.py
setup.py
share/eduvpn/builder/mainwindow.ui

Yes the version numbers are confusing. The next pre-release will actually be a release candidate.

3.3.1 pre-release

---

doc/build.sh
doc/md/installation.md
install.sh

Following the docs can be confusing which distribution/codename to pick.
This script aims to fix that by installing if the distro + codename is supported.

Doc: Add an install script

---

eduvpn/data/share/applications/org.eduvpn.client.desktop

Fix panel icon on ubuntu 24.04+

---

pyproject.toml
setup.cfg
setup.py

Unfortunately we can't use pyproject.toml for everything just yet

Building: Add setup.cfg + setup.py for backwards compat

---

eduvpn/ui/ui.py

UI: Add a CTRL+q quit shortcut

---

eduvpn/app.py

Can be removed once common 2.1.0 is released

App: Fix mypy RefreshList import

---

eduvpn/cli.py
eduvpn/server.py
eduvpn/ui/search.py

To avoid unnecessary dependency of CLI on Gtk.

Move ServerGroup and group_servers from ui.search to server
