eduvpn/util.py, tests/actions/test_activate.py, tests/actions/test_switch.py, tests/test_actions.py, tests/test_notify.py
Just testing system DBUS presence is not sufficient to ensure a proper
test environment.
=> test notification service availability

Makefile, doc/introduction.rst, eduvpn/ui/ui.py, share/eduvpn/builder/mainwindow.ui
- Add a server when pressing enter in LC
- Enter can be used when there is only one choice left in eduVPN
Small additional fixes:
- Fix bug with initialising the backend twice, introduced during the merge of the last PR
- Use system site packages in a Python virtual env
- Update documentation now make targets are renamed
make gui -> make eduvpn-gui
make lc -> make letsconnect-gui
=> issue #279

eduvpn/app.py, eduvpn/interface.py, eduvpn/network.py, eduvpn/server.py, eduvpn/state_machine.py, eduvpn/ui/__main__.py, eduvpn/ui/search.py, eduvpn/ui/ui.py, eduvpn/ui/utils.py, eduvpn/utils.py, tests/test_state_machine.py
This PR addresses #258 by providing the framework and partial implementations of the state machines running the application, as well as their interaction with the UI.
A specific goal is to separate the state of the application into independent parts. To that end, the state of the network and interface have been separated into two state machines, as they both operate more or less independently. The complete app state is collected in the Application type.
The state machine is wrapped in a type with the goal of providing a nicer api to the UI through the transition registration decorators. This part is somewhat complex, but IMHO leads to a nicer api for UI. For one, it cleanly separates the UI from the app state, while also avoiding long lists mapping methods to events.
From here I'll work …
=> Introduce state machines

eduvpn/app.py, eduvpn/interface/event.py, eduvpn/interface/state.py, eduvpn/interface/utils.py, eduvpn/network.py, eduvpn/server.py, eduvpn/ui/search.py, eduvpn/ui/ui.py
If you've used the app before, the previously configured connections are now shown to reconnect immediately.
This also includes a cleanup of the type hints for the various server types, I'm sorry about the noise this causes but I hope this clears some things up.
=> Show previously configured connections on app startup

MANIFEST.in, setup.py
Having `__init__.py` in the tests folder causes `find_packages` to consider it a package to be installed.
=> Prevent tests from being installed

eduvpn/settings.py, eduvpn/utils.py
Allow users to use a different configuration directory using the $XDG_CONFIG_HOME environment variable from the xdg base directory spec: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html/
=> Allow user defined config directory using $XDG_CONFIG_HOME

docker/pytest_centos_8.docker, docker/rpm_centos_8.docker
Fixes part of #442
We can use Centos stream in a different PR. For now, we need to get the builds working again.
Centos 8 is EOL, to fix builds for now use the vault archive, see: https://techglimpse.com/failed-metadata-repo-appstream-centos-8/
=> Centos Docker: Use the vault archive

eduvpn/interface/event.py
Fixes #439 
This commit sets the `ready_for_oauth_setup` state before the browser is
opened. In certain browsers (e.g. palemoon) the `webbrowser.open` call
does not terminate after the url is opened, but instead stays alive
until the browser window is closed.
This results in an invalid state:
```
2022-02-07 11:27:14,529 - MainThread - ERROR - eduvpn.app - app.py:137 - invalid interface state transition: <OAuthSetupPending server=<InstituteAccessServer 'Radboud University'>> -> oauth_setup_success
```
We can test the difference in behaviour of `webbrowser.open` with:
```bash
BROWSER=firefox python -m webbrowser "google.com" (exits immediately)
BROWSER=palemoon python -m webbrowser "google.com" (waits up until closed)
BROWSER=chromium python -m webbrowser "google.com" (exits immediately or …
```
=> OAuth: Set oauth ready before webbrowser open

.github/workflows/containers.yml, docker/pytest_centos_stream8.docker, docker/rpm_centos_stream8.docker
Fixes #442 
This commit updates the docker images used in the CI to use CentOS
stream 8. This is because CentOS 8 is EOL.
Note that these are unofficial images as the official images do not support stream (yet).
=> CI: Move from CentOS to CentOS stream8

eduvpn/network.py, eduvpn/nm.py, eduvpn/ui/stats.py, eduvpn/ui/ui.py, eduvpn/utils.py, share/eduvpn/builder/mainwindow.ui, tests/test_stats.py
Fixes #248 
This commit adds a connection info expander to the UI.
Uses the NM api for querying, except where I could not find any
functions (e.g. rx and tx bytes, which are gathered from standard file
locations).
If it cannot find the data, as this is not foolproof, it will set it
to N/A, the application will keep working.
Note that glade changed the property names from `_` to `-`, but this
still works on the VMS. Apparently `_` are an old format that is not
used any more in glade.
=> UI: Add a connection info expander

eduvpn/storage.py, tests/test_storage.py
Unfortunately, the issue only happens on Python 3.6 which is EOL as of this year.
I prefer to keep datetimes timezone-aware, we can get rid of these fixes when we remove 3.6 support.
=> Fix issue #462

eduvpn/nm.py
During the fix in ccc7319212e2c437d0ae78c8e35f75932b506f42 the `Ovpn.write` method was rewritten to allow a config that is a list. The config list is generated by `Ovpn.parse`, which must be used instead of the constructor.
This was tested from commandline with `eduvpn-cli configure`.
This fixes #470
=> Fix issue #470

eduvpn/nm.py, eduvpn/ui/stats.py
The duration was really buggy, sometimes it shows the duration since 1st january 1970, since NM can return 0. Additionally, the duration is not reset upon disconnect+connect again with the toggle. This pr fixes that by making sure we use the connection with the saved connection id and we retry the timestamp when networkmanager returns 0. If network manager still returns 0 (or None), we show N/A in the UI.
=> Stats: Fix duration weirdness

eduvpn/nm.py
OpenVPN has autoconnect enabled, however autoconnect is not used for VPN profiles, see https://lazka.github.io/pgi-docs/#NM-1.0/classes/SettingConnection.html#NM.SettingConnection.props.autoconnect
This means that for OpenVPN, when disabling the VPN in the client and then rebooting, networkmanager will not enable the vpn connection. However, for wireguard right now it will re-enable the vpn even though the user has said to disconnect from it (because wireguard is not managed as a VPN profile by NM). This simply disables autoconnect so that networkmanager doesn't force it to reconnect when the machine has e.g. rebooted.
Reported by @fkooman
=> Wireguard: Disable autoconnect to match OpenVPN behaviour

tests/test_nm.py
Tests would fail with
```python
______________________________________________________________ TestNm.test_get_add_connection ______________________________________________________________
self = <tests.test_nm.TestNm testMethod=test_get_add_connection>
def test_get_add_connection(self):
client = get_client()
ovpn = Ovpn.parse(mock_config)
>       simple_connection = import_ovpn(ovpn, mock_key, mock_cert)
E       TypeError: import_ovpn() takes 1 positional argument but 3 were given
tests/test_nm.py:25: TypeError
_________________________________________________________________ TestNm.test_import_ovpn __________________________________________________________________
self = <tests.test_nm.TestNm testMethod=test_import_ovpn>
def test_import_ovpn(self):
ovpn = Ovpn.parse(mock_config)
> …
```
=> Make tests pass when running with NetworkManager

eduvpn/nm.py, eduvpn/ui/stats.py, eduvpn/ui/ui.py, share/eduvpn/builder/mainwindow.ui
- download/upload: No longer gets reset upon expander toggle
- download/upload: Wireguard support
- Duration: removed due to inability to get it working. Nm's timestamp
is NOT the time the connection was last set to connected, it gets
updated periodically. There is no simple way to implement this properly without some NetworkManager statistic, which I can't find.
Reported by @fkooman
=> Connection Info: Remove duration and down/up fixes

eduvpn/config.py, eduvpn/nm.py, eduvpn/ui/ui.py, share/eduvpn/builder/mainwindow.ui
This adds an option so that connections are configured for the current user only instead of system-wide.
Fixes #488 
Disabled by default because this is also what networkmanager does
=> NM: Make connections optionally user only

eduvpn/app.py, eduvpn/session.py
The state transition was done before we returned the right state (`SessionActiveState`)
Fixes #496
=> Fix server info launch

CHANGES.md, eduvpn.spec, setup.py
IMO 3.1 should be released asap. Some issues are still left open with the 3.1 milestone but these are better fit for future releases where we use the Go library.
3.1 and not 3.0.1 because there are enough changes and the Windows client will release 3.1 soon too
=> Prepare 3.1

eduvpn/server.py
- This fixes backwards compatibility with older servers that
e.g. still have `vpn_proto_preferred`
Fixes #499
=> Server: Add handling for unknown keyword arguments

eduvpn/nm.py
Fixes #505 
DNS entries are optional, e.g. when `defaultGateway` is `false` or the entries are removed from the config.
=> NM: DNS entries for WireGuard are optional

eduvpn/config.py, eduvpn/nm.py, eduvpn/ui/ui.py, share/eduvpn/builder/mainwindow.ui
Fixes #504 
Forces nm to set system wide to `False`, thus only giving permission to the current user only. Users can still enable this in the settings. I renamed the setting to be more in line with networkmanager and to also give new users the new setting by default for security.
=> Config + NM + UI: Set connection to user only by default

doc/md/installation.md
This commit updates the the link from the former, unofficial nixos wiki page to the new https://wiki.nixos.org
ref: NixOS/foundation#113
=> docs: point to official nixos wiki

eduvpn/app.py, eduvpn/keyring.py, eduvpn/ui/ui.py
Fixes: #587
This makes sure that for the CLI the keyring is only used when used. For the GUI it's still used on startup (if the UI is opened)
=> Keyring: Improve detection and stop triggering it for every command

eduvpn/data/share/applications/org.eduvpn.client.desktop, eduvpn/data/share/applications/org.letsconnect-vpn.client.desktop
During packaging eduVPN for Gentoo Linux the distro maintainers suggested to add the category `Network;Dialup` to the desktop file. Currently we are applying this patch downstream, but it may be useful for other users, too. So I would like to request you considering to apply this patch upstream.
=> Add Category to desktop files

eduvpn/i18n.py, eduvpn/settings.py
=> i18n: Fallback to english in retrieve_country_name
